version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: gestaogor_backend_prod
    ports:
      - "3000:3000"
    environment:
      # Essas variáveis devem ser configuradas para apontar para o servidor de Banco de Dados específico
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-5432}
      - PORT=3000
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args: # Define a URL do backend. Em produção, você pode querer colocar o seu IP público ou domínio aqui.
    container_name: gestaogor_frontend_prod
    ports:
      - "80:80"
    depends_on:
      - server
