server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Todas as rotas que não forem arquivos devem apontar para o index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tratamento de cache para assets estáticos para melhor performance
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
